name: Daily News Scraper

on:
  schedule:
    # Runs at 2 PM UTC daily (adjust timezone as needed)
    - cron: '0 14 * * *'
  workflow_dispatch: # Allows manual triggering

jobs:
  scrape-news:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r News_classification_UpDown/requirements.txt
        
    - name: Run news scraper
      run: |
        cd News_classification_UpDown
        python daily_news.py
        
    - name: Commit and push results
      run: |
        git config --local user.email "wirolo29837@gmail.com"
        git config --local user.name "ZoeChenCH"
        git add News_classification_UpDown/daily_news/
        git diff --staged --quiet || git commit -m "Update news data - $(date)"
        git push
