name: Daily News Scraper

on:
  schedule:
    # Runs at 10 AM UTC daily (adjust timezone as needed)
    - cron: '0 10 * * *'
  workflow_dispatch: # Allows manual triggering

jobs:
  scrape-news:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r News_classification_UpDown/requirements.txt
        
    - name: Run news scraper
      run: |
        cd News_classification_UpDown
        python daily_news.py

    - name: Commit and push results
      run: |
        git config --local user.email "wirolo29837@gmail.com"
        git config --local user.name "ZoeChenCH"
        # Stage all changes
        git add .
        
        # Only proceed if there are staged changes
        if ! git diff --staged --quiet; then
          echo "Committing changes..."
          git commit -m "Update news data - $(date)"
          
          # Simple push with force-with-lease (safer than force)
          git push origin main || {
            echo "Push failed, pulling and trying again..."
            git pull origin main --strategy=recursive -X ours
            git push origin main
          }
        else
          echo "No changes to commit"
        fi
