name: Daily News Scraper

on:
  schedule:
    # Runs at 8 AM Taiwan time daily (0 AM UTC)
    - cron: '0 0 * * *'
    
  push: 
    branches: [main]
    
  workflow_dispatch: # Allows manual triggering

jobs:
  scrape-news:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r News_classification_UpDown/requirements.txt
        
    - name: Run news scraper
      run: |
        cd News_classification_UpDown
        python daily_news.py

    - name: Commit and push results
      run: |
        git config --local user.email "wirolo29837@gmail.com"
        git config --local user.name "ZoeChenCH"
        git config --local pull.rebase false
        git config --local merge.ours.driver true  # Handle conflicts by keeping our version
        
        git add .
        
        # Only proceed if there are staged changes
        if ! git diff --staged --quiet; then
          echo "Committing changes..."
          git commit -m "Update news data - $(date)"

          echo "Syncing with remote repository..."
          git fetch origin main

          if ! git merge-base --is-ancestor origin/main HEAD; then
            echo "Remote has new changes, merging..."
            git merge origin/main -m "Merge remote changes with news update"
          fi

          echo "Pushing changes..."
          git push origin main

        else
          echo "No changes to commit"
        fi
