name: Daily News Scraper

on:
  schedule:
    # Runs at 10 AM UTC daily (adjust timezone as needed)
    - cron: '0 10 * * *'
  workflow_dispatch: # Allows manual triggering

jobs:
  scrape-news:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r News_classification_UpDown/requirements.txt
        
    - name: Run news scraper
      run: |
        cd News_classification_UpDown
        python daily_news.py

    - name: Commit and push results
      run: |
        git config --local user.email "wirolo29837@gmail.com"
        git config --local user.name "ZoeChenCH"
        git pull origin main --rebase
        git add News_classification_UpDown/daily_news/
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Update news data - $(date)"
          # Try to push, with retry logic
          max_attempts=3
          attempt=1
          while [ $attempt -le $max_attempts ]; do
            if git push origin main; then
              echo "Successfully pushed on attempt $attempt"
              break
            else
              echo "Push failed on attempt $attempt, pulling and retrying..."
              git pull origin main --rebase
              attempt=$((attempt + 1))
              sleep 5
            fi
          done
          
          if [ $attempt -gt $max_attempts ]; then
            echo "Failed to push after $max_attempts attempts"
            exit 1
          fi
        fi
